### ISSUE TITLE
Username mapping schemes

### ISSUE THREAD

**Issue by laurivosandi** [codemowers/passmower#39]
The username mapping schemes could be improved a bit:

* Random generated ones u12345 this is already supported
* Prompt user for username during singup, this is already implemented. Form could be prepopulated preferred username claim from upstream IdP though
* Best effort mapping of preferred username, if username is taken prompt user

**Comment by veebkolm** [comment]
Implemented pre-populating username from upstream IdP (GitHub).
If user tries to submit that, and it exists, error is displayed and value is kept so user can change that.
![image](https://github.com/codemowers/passmower/assets/25956365/37ae06c7-0799-4fdf-8468-3a007700761e)
